version: "2.3"

services:
    search_market_place-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/search_market_place/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/search_market_place:rw
        ports:
          - 8080:8080
        working_dir: /search_market_place
        entrypoint:
          - ./tests/run_as_user.sh
