worker-threads: 2
worker-fs-threads: 2
logger-level: debug

is-testing: true

server-port: 8080

# change to URI of your postgres database
pg-connection: postgresql://testsuite@localhost:15433/category_db_1