components:
  schemas:
    OutputJsonFormat:
      type: object
      additionalProperties: false
      properties:
        data:
          type: string
          description: Строковые данные из Proto сообщения
        number:
          type: integer
          description: Числовое значение из Proto сообщения
        is_valid:
          type: boolean
          description: Булево значение из Proto сообщения
      required:
        - data
        - number
        - is_valid
